### ISSUE TITLE
Дополнительный функционал

### ISSUE THREAD

**Issue by apankov** [AlexeyKorkoza/todo-list#37]
Алексей,
разработайте функционал, позволяющий "хозяину" группы тудушек давать доступ другим участникам системы. Пример из жизни - муж и жена могут пользоваться общим пространством для ведения домашних дел.
(sharing)

**Comment by AlexeyKorkoza** [comment]
Я понял, сделаю.

**Comment by AlexeyKorkoza** [comment]
See, #40
